apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: hnp
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    livenessProbe:
      httpGet:
        path: /abc
        port: 80
      initialDelaySeconds: 15
    ports:
      - containerPort: 80