apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod4
  namespace: hnp
spec:
  nodeSelector:
    disk: ssd
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80