apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-and-mem
  namespace: hnp
spec:
  hard:
    requests.cpu: 400m
    requests.memory: 200Mi
    limits.cpu: 600m
    limits.memory: 500Mi
    requests.storage: 500Gi
    ssd.storageclass.storage.k8s.io/requests.storage: 300Gi
    standard.storageclass.storage.k8s.io/requests.storage: 1Ti
    pods: 10
    replicationcontrollers: 5
    secrets: 10
    configmaps: 10
    persistentvolumeclaims: 4
    services: 5
    services.nodeports: 2
    services.loadbalancers: 1
    ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 2
