apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 2
  selector:
    app: item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
          - containerPort: 80