
# k create namespace hnp

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: hnp
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80