
services:
  nexus:
    image: sonatype/nexus3:3.85.0
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
    # environment:
      # - HTTP_PROXY=http://host.docker.internal:10808
      # - HTTPS_PROXY=http://host.docker.internal:10808
      # - NO_PROXY=localhost,127.0.0.1,::1
    volumes:
      - ./nexus_storage:/nexus-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"] 
      interval: 30s
      timeout: 10s
      retries: 3


# it uses system proxy, in setting realm add bareer auth with higher priority