apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp-front
  namespace: hnp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: item
  template:
    metadata:
      labels:
        app: item
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: In
                values:
                - "true"
      containers:
      - name: nginx
        image: nginx:1.27.2
        ports:
        - containerPort: 80
          name: http
