
# k create serviceaccount -n hnp hnp

apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: hnp
spec:
  serviceAccountName: hnp
  containers:
  - name: test
    image: curlimages/curl
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  - name: proxy  # we use this image for security test
    image: seeq13/datalab-kubectl-proxy

# then we can use this command to connect to api server:
# k exec -it -n hnp test -- curl localhost:8001