apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: hnp
spec:
  serviceAccountName: hnp
  containers:
  - name: test
    image: curlimages/curl
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]

