apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hnp-services-read-binding
  namespace: hnp2
subjects:
- kind: ServiceAccount
  name: hnp
  namespace: hnp2   # we can use multiple subject
roleRef:
  kind: Role
  name: hnp-services-read
  apiGroup: rbac.authorization.k8s.io
