apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # Start with one replica
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m" # Request 50 millicores (0.05 CPU core)
            memory: "64Mi"
          limits:
            cpu: "100m" # Limit to 100 millicores (0.1 CPU core)
            memory: "128Mi"
